Scripts/Core: New AcquSubmit, clean "build" dir to get it working

diff --git a/acqu_core/scripts/AcquSubmit b/acqu_core/scripts/AcquSubmit
--- a/acqu_core/scripts/AcquSubmit
+++ b/acqu_core/scripts/AcquSubmit
@@ -1,158 +1,206 @@
+#!/usr/bin/perl
+use strict;
+use warnings;
+use Getopt::Long;
+
+use Cwd qw(abs_path getcwd);
+use File::Path qw(rmtree mkpath);
+use File::Basename qw(basename);
+
+my $filelist = '-';             # default STDIN
+my $outputdir;                  # needs to be provided on cmd line
+my $clean = 0;
+my $help = 0;
+my $directio;
+my $cwd = getcwd;
+my $QSUB_BIN = 'qsub';
+my $ACQUROOT_BIN = which('AcquRoot');
+# parse options
+Getopt::Long::Configure(qw(gnu_getopt));
+GetOptions(
+           'help|h' => \$help,
+           'clean|c' => \$clean
+          ) or print_help();
+
+
+# parse arguments
+if (@ARGV==1 || @ARGV==2) {
+  $outputdir = $ARGV[0];
+  if (@ARGV==2) {
+    $filelist = $ARGV[1];
+  }
+} else {
+  print_help();
+}
+
+
+&main;
+
+sub main {
+  # check some things before submission
+  die "AcquRoot not found in PATH=$ENV{PATH}" unless defined $ACQUROOT_BIN;
+  warn "Warning: Current working directory '$cwd' does not end with 'acqu_user'" unless $cwd =~ /acqu_user$/;
+
+  # check for DirectIO flag
+  my $ROOTsetup = 'data/ROOTsetup.dat';
+  my $haveROOTsetup = -f $ROOTsetup ? 1 : 0;
+  my $ROOTsetupMC = 'data/ROOTsetupMC.dat';
+  my $haveROOTsetupMC = -f $ROOTsetupMC ? 1 : 0;
+
+  die "Error: Neither $ROOTsetup nor $ROOTsetupMC file found. Either you're in the wrong working directory".
+    " or you need to create a symlink to AR.dat or AR-MC.dat (or similar top-entry config file for rundata or MC)".
+    " below the data/ config folder."
+    unless $haveROOTsetup or $haveROOTsetupMC;
+
+
+  # data files might use DirectIO mode
+  if($haveROOTsetup) {
+    open(my $cfg_fh, "<$ROOTsetup") or die "Can't open $ROOTsetup: $!";
+    while (<$cfg_fh>) {
+      next if /^#/;
+      if (/^UseDirectIO:/) {
+        $directio = 1;
+        last;
+      }
+    }
+    close $cfg_fh;
+  }
+
+  # read in the filelist, check for more errors
+  open(my $inputfiles_fh, "<$filelist") or die "Can't open filelist $filelist: $!";
+  my $n = 0;
+  my @files;
+  while (my $inputfile = <$inputfiles_fh>) {
+    $n++;
+    chomp $inputfile;
+    unless(-f $inputfile) {
+      warn "Warning: Inputfile $inputfile does not exist, skipping.";
+      next;
+    }
+    unless($inputfile =~ /\.(dat|dat\.xz|root)$/) {
+      warn "Warning: Inputfile $inputfile does not end with .dat[.xz] or .root, skipping.";
+      next;
+    }
+    my $ismc = $inputfile =~ /\.root$/ ? 1 : 0;
+    if($ismc && !$haveROOTsetupMC) {
+      die "Error: Cannot analyze MC .root file '$inputfile' without file '$ROOTsetupMC'.";
+    }
+    if(!$ismc && !$haveROOTsetup) {
+      die "Error: Cannot analyze rundata file '$inputfile' without file '$ROOTsetup'.";
+    }
+
+    my $runnumber;
+    if ($ismc) {
+      # don't try to extract runnumbers for MC files...
+      $runnumber = $n;
+    } else {
+      $runnumber = extract_runnumber($inputfile);
+      unless(defined $runnumber) {
+        warn "Cannot extract runnumber from $inputfile, using input linenumber $n instead";
+        $runnumber = $n;
+      }
+    }
+    $inputfile = abs_path($inputfile);
+    push(@files, [$inputfile, $runnumber]);
+    #print "Input: $inputfile\n";
+  }
+  close $inputfiles_fh;
+
+  # clean/create outputdir
+  if ($clean) {
+    print "Deleting outputdir $outputdir\n";
+    rmtree([$outputdir]) or die "Error: Outputdir $outputdir was not deleted.";
+  }
+  die "Error: Output dir '$outputdir' already or still exists. Maybe use --clean?" if -e $outputdir;
+  mkpath(["$outputdir/log", "$outputdir/root"]) == 3 # three folders should be created
+    or die "Error: Cannot create log and root folders below outputdir $outputdir";
+
+
+  # for jobs, make it absolute
+  $outputdir = abs_path($outputdir);
+  $ACQUROOT_BIN = abs_path($ACQUROOT_BIN);
+
+  # finally submit the jobs
+  my $submitted = 0;
+  for my $f (@files) {
+    submit_file($f->[0], $f->[1]);
+    $submitted++;
+  }
+
+  print "Submitted $submitted jobs.\n";
+}
+
+sub extract_runnumber {
+  my $f = shift;
+  if ($f =~ /_(\d+?)\.dat/) {
+    return $1;
+  }
+  return undef;
+}
+
+sub which {
+  my $cmd = shift;
+  open(my $p, "which $cmd |") or die "Can't open which: $!";
+  my @lines = <$p>;
+  close $p;
+  my $exit_value = $? >> 8;
+  if ($exit_value != 0 || @lines != 1) {
+    return undef;
+  }
+  chomp $lines[0];
+  return $lines[0];
+}
+
+sub submit_file {
+  my $inputfile = shift;
+  my $runnumber = shift;
+
+  my $ncpus = $inputfile =~ /\.(dat|root)$/ || ($directio && $inputfile =~ /\.xz$/) ? 1 : 2;
+  my $rootfile = $inputfile =~ /\.root$/ ? "--rootfile" : ""; # AcquRoot is too stupid to detect this...
+
+  my $basename = basename($inputfile);
+  my $user = $ENV{USER};
+  # open pipe to qsub
+  open(my $qsub, "| $QSUB_BIN >/dev/null")
+    or die "Can't open pipe to $QSUB_BIN: $!";
+  print $qsub <<__BATCHSCRIPT;
 #!/bin/bash
-
-# A shell script to submit farm jobs
-
-# 1st version Ken Livingston, Nov 2007
-# Modified from Jlab auger to pbs / torque - Ken Livingston Feb 2014
-
-# function defs first,  main script below that.
-
-
-exe=`basename $0`
-print_usage()
-{
-    echo
-    echo "Description: A shell script to submit jobs to a pbs / torque batch farm queue."
-    echo
-    echo "Usage: $exe [-r] [-s sleep] [-m <maxjobs>] <jobdir>|<jobfile>"
-    echo
-    echo "Options:"
-    echo "  -m <maxjobs>   Set the maximum no of user owned jobs on the farm (default = 500)"
-    echo "  -s <sleep>     Sleep time(s) between submitting jobs (default = 1s)"
-    echo "  -r             Submit jobs in reverse order to their directory listing in <jobdir> "
-
-    echo "Attempts to run qsub to submit <jobfile>, or all the *.sub files in <jobdir>"
-    echo "For each jobfile, a test is made to see if jobfile.done exists. If so, the assumption is"
-    echo "that the file has already been submitted. To allow resubmission, the .done file must be removed manually" 
-    echo "The log of the each jsub command is put in <jobfile>.done"
-    echo "Furthermore, no jsub commands will be executed until there are less than <maxjobs> jobs pending" 
-    echo "or running on the farm (counted using the jobstat comand)"
-    echo "The maximum no of jobs can be adjusted using the -m option. (default = 500)"
-    echo "If there are more than <maxjobs>, the script will loop, testing every hour until it is able to"
-    echo "submit another job."
-    echo 
-    echo "For each jobs to be submitted this script checks for the existence of the data files on the local farm RAID."
-    echo 
-    echo "Examples:"
-    echo
-    echo "$exe jobs/g13/pass0/v7/batch1/runs53764-53783.sub"
-    echo "Submits  jobs/g13/pass0/v7/batch1/runs53764-53783.sub with result in jobs/g13/pass0/v7/batch1/runs53764-53783.sub.done"
-    echo
-    echo "$exe -m 1000 jobs/g13/pass0/v7/batch1"
-    echo "Submits all .sub files in jobs/g13/pass0/v7/batch1, with logs in corresponding .done files,"
-    echo "also increasing the maximum no of jobs to 1000." 
-    echo 
-    exit;
+#PBS -N Acqu_$runnumber
+## Send eMail if job aborts
+#PBS -m a
+## Send eMail when job begins
+##PBS -m b
+## Send eMail if job ends
+##PBS -m e
+#PBS -M $user\@kph.uni-mainz.de
+#PBS -V
+#PBS -l walltime=2:00:00
+#PBS -j oe
+#PBS -o $outputdir/log/$basename.log
+#PBS -q batch
+#PBS -l ncpus=$ncpus
+echo INPUTFILE: $inputfile
+cd $cwd
+$ACQUROOT_BIN --nolog --batch $rootfile \\
+  --batchdir $outputdir/root/ \\
+  --directory $outputdir/root/ \\
+  --datafile $inputfile
+__BATCHSCRIPT
+  close $qsub or die "Cannot close pipe to qsub";
 }
 
-init_values()
-{
-#set the defaults
-    sleeptime=0;
-    default_maxq="3000";
-    rev="";
-    maxq="${default_maxq}";
-    waittime="5m";
+sub print_help {
+  print <<__EOF;
+Usage: AcquSubmit [--clean] <outputdir> [<filelist>|-]
+
+Submit jobs with qsub running AcquRoot on files in provided <filelist>
+(or read it from STDIN), output goes to <outputdir> (will be created
+and must not exist already). Needs to be run from "acqu_user"
+directory with proper data/ symlink config folder.
+
+Options:
+
+  --clean   Recursively delete <outputdir> before submission.
+__EOF
+  exit 255;
 }
-
-#  Function to set the command line options
-function set_option {
- 	case $1 in
-        R)
-            resubmit=1
-            ;;
-	    m)
-	    maxq="${OPTARG}" ;;
-	    s)
-	    sleeptime="${OPTARG}" ;;
-	    r)
-	    rev="-r" ;;
-            *)
-	    print_usage ;;
-	esac
-    shift $[OPTIND-1]
-} 
-
-################################################################################################
-#MAIN SCRIPT STARTS HERE
-
-if [ $# -lt 1 ]; then
-     print_usage;
-fi
-
-init_values;
-
-#parse the command options and set variables accordingly
-while getopts "m:s:r:R" opt ; do 
-    set_option $opt  
-done
-shift $[$OPTIND-1]
-
-#work out if we have a file or directory ( or neither)
-if [ -f "$1" ]; then
-    #make a filelist with a single file, for consistency
-    dir=`dirname $1`
-    rm -f ${dir}/allsubs.dat
-    echo $1 > ${dir}/allsubs.dat
-else
-    dir=$1
-    if [ -d "$dir" ]; then
-	#make a filelist of all files
-	rm -f ${dir}/allsubs.dat
-	ls $rev $dir/*.sub > ${dir}/allsubs.dat
-    else
-	echo "Fatel Error: $1 doesn't seem to exist"
-	print_usage
-    fi
-fi
-
-#loop over all files in ${dir}/allsubs.dat
-
-if [ "$resubmit" == "1" ]; then
-    echo "Resubmitting"
-    rm ${dir}/*.done
-    rm ${dir}/Acqu_*
-fi
-
-while read subfile
-do
-    #if not already submitted (ie no .done file)
-    if [ ! -f "${subfile}.done" ]; then
-
-	#copy the files to the local raid if required by getting the info from the comments at top of the jobfile
-	#get the stuff after the keyword in each requiredline
-	LocalDir=`gawk -v f1="#InputDir: " '{if($0~f1){sub(f1,"");print $0}}' ${subfile}`
-	InputFile=`gawk -v f1="#InputFile: " '{if($0~f1){sub(f1,"");print $0}}' ${subfile}`
-
-	#if there are files to be copied (ie non zero list of files) 
-	if [ ! -z $InputFile ]; then
-	    echo "Checking for file on local RAID: $InputFile"
-
-	    LocalFile=${LocalDir}"/"${InputFile}
-	    
-	    if [ ! -f $LocalFile ]; then
-		echo "Not found as $LocalFile"
-		exit 1
-	    else
-		echo "Found $LocalFile"
-	    fi
-	fi
-	
-	#OK to go
-	qsub $subfile >& ${subfile}.done
-	if [ $? -ne 0 ]; then
-		echo "Error submitting job:"
-		cat  ${subfile}.done
-		echo "Aborting..."
-		rm ${subfile}.done
-		exit 1
-	fi
-	sleep $sleeptime
-    else
-	echo "$subfile was submitted previously."
-    fi
-
-done < ${dir}/allsubs.dat
-
-
-exit;
